#!/bin/bash 

function showpatch {
  cat $1 | colordiff | less -RS
}

function deletefiles {
  find . -type f -name "$1" -delete 
}


function getwav {
  youtube-dl -x --audio-format wav $1 
}

function npm-do { (PATH=$(npm bin):$PATH; eval $@;) }

grep='grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,node_modules,vendor,app_bundles} --exclude={*.orig,*.swp}'

prettyjson() {
  python -m json.tool | pygmentize -l json
}

triggercodeship() {
  touch tmp
  hg add tmp
  hg commit -m "Trigger Codeship"
  hg rm tmp
  hg commit --amend -m "Trigger Codeship"
}

tsarea() {
  gnome-screenshot -a
}

alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'
alias pbtesseract='sleep 2; gnome-screenshot -ac; xclip -selection clipboard -t image/png -o > /tmp/_pbcopy_tesseract.png ; tesseract /tmp/_pbcopy_tesseract.png /tmp/_pbcopy_tesseract --l eng > /dev/null; sleep 2; cat /tmp/_pbcopy_tesseract.txt  | pbcopy'
